### ISSUE TITLE
CSS path troubles

### ISSUE THREAD

**Issue by saprentice** [dita4publishers/dita4publishers#31] opened 2018-06-02 01:10 UTC
Running a default build ..

`dita --input=mymap.ditamap --output=out/epub --format=epub`

.. results in the references in the HTML to the CSS files to be invalid ..

`<link rel="stylesheet" type="text/css" href="css/csscommonltr.css" />`

There's an extra "css" tacked on to the CSS filename .. css/**css**commonltr.css.

If the CSS path is specified in the command line, it seems to have no effect on the resulting HTML ..

`dita --input=mymap.ditamap --output=out/epub --format=epub --args.csspath=zzz`

It does look like this is working correctly (in OT 2.4 and later) for HTML5 and XHTML targets, so I think there's something funky in the D4P code that's forcing "css" as the path, and adding the "css" prefix to the filename.

**Comment by drmacro** [comment] 2018-11-05 10:48
This was an issue with the $CSSPATH variable not having a trailing "/", which the code (as copied from the base OT) assumed.

I've added a check for that the issue is resolved in my tests.

**Comment by drmacro** [comment] 2018-11-06 14:51
This should be corrected in release 1.0.0RC27

**Closed by drmacro** 2018-11-06 14:51 UTC
